### ISSUE TITLE
这个是游戏吗？

### ISSUE THREAD

**Issue by Cyang39** [miaonot/CattleFarm#1]
因缺思厅，怎么玩

**Comment by miaonot** [comment]
並不是遊戲呢，只是一個農場的管理系統。要一起來做麼？

**Comment by Cyang39** [comment]
農場的管理系統
这。。。。
I‘m watching....

**Comment by miaonot** [comment]
嗯。有興趣了就一起來。畢竟我們這邊@laohantuiche不怎麼寫代碼

**Comment by Cyang39** [comment]
这是要做神马啊？毕业设计吗…（⊙＿⊙；）…

**Comment by miaonot** [comment]
給大師的一個親戚做的，算是外包項目吧。

**Comment by Cyang39** [comment]
真是厉害，你们要是写API文档的话，我也许会commit一下，
技能树去点前端了，Java不是太感冒

**Comment by miaonot** [comment]
呃，函數的功能都註釋在裏面了，剛開始寫大概不會去做整理_(:3」∠)_

**Comment by hongri1995930** [comment]
给我们撸个漂亮点的前端嘛，直接java写太丑了

**Comment by Cyang39** [comment]
是要做Web App吗。。。。@hongri1995930
另外我也不懂设计啊，UI直接Bootstrap里拉来就用

**Comment by hongri1995930** [comment]
@HuQinyang 做web app 桌面端就不怎么用了吧，233， 前端桌面设计我倒是一点没看过

**Comment by Cyang39** [comment]
@hongri1995930 前端是指**网页**前台，主要包括`html`标记、`CSS`样式、`JavaScript`脚本，而后台可以有其他语言实现，常用的是`Perl`、`PHP`、`Java`、`Python`，如果要做`web app`的话就需要服务器了

**Comment by hongri1995930** [comment]
@HuQinyang 666，大师计划以后可以有移动客户端，那直接web app就好了

**Comment by Cyang39** [comment]
@hongri1995930 现在创业项目一般最开始的成型产品都是**微信服务号**，其实就是做Web App了![滑稽](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png?t=20140803)

**Comment by hongri1995930** [comment]
@HuQinyang 帮我开发一下留学工大可好
![687474703a2f2f7462322e62647374617469632e636f6d2f74622f656469746f722f696d616765732f666163652f695f6632352e706e673f743d3230313430383033](https://cloud.githubusercontent.com/assets/12499717/11625055/f4fa9d68-9d12-11e5-8051-95fe17d053b9.png)

**Comment by Cyang39** [comment]
我看了一下，这个是`订阅号`不是`服务号`![汗](http://tb2.bdstatic.com/tb/editor/images/face/i_f08.png)，本来以为还能拿来耍耍
@hongri1995930

**Comment by hongri1995930** [comment]
@HuQinyang 订阅号可以一键升级服务号，但是好像权限更小了，我们不适用，你可以去搞个服务器连接着玩呀

**Comment by Cyang39** [comment]
@hongri1995930 服务号每年要付钱的，**400元/年**，阿里最近学生云服务器优惠，也就**60元/半年**，带有一个月**10G**输出流量。腾讯那么坑，哪里玩得起![大哭](http://tb2.bdstatic.com/tb/editor/images/face/i_f09.png)

**Comment by hongri1995930** [comment]
![2015-12-07 19 07 20](https://cloud.githubusercontent.com/assets/12499717/11625461/25015ec2-9d16-11e5-9c26-0d73a2236a0b.png)

**Comment by Cyang39** [comment]
@hongri1995930 对啊，50多就可以拿半年了

**Comment by hongri1995930** [comment]
@HuQinyang 赶紧买买买！

**Comment by Cyang39** [comment]
@hongri1995930 我有一张20元的券，直接可以换**两个月**，但是我没什么用啊。

**Comment by hongri1995930** [comment]
@HuQinyang 开个网站让老汉去爬
![687474703a2f2f7462322e62647374617469632e636f6d2f74622f656469746f722f696d616765732f666163652f695f6632352e706e673f743d3230313430383033](https://cloud.githubusercontent.com/assets/12499717/11625607/32d9aeea-9d17-11e5-816a-a8227c1e4843.png)

**Comment by Cyang39** [comment]
@hongri1995930 我的券就是买**域名**送的，[胡钦炀的博客](http://huqinyang.com)，我不开发后端，不需要服务器。

**Comment by hongri1995930** [comment]
@HuQinyang 我去逛过了，有意思，感觉有一套教程在博客上啊

**Comment by Cyang39** [comment]
@hongri1995930 其实只是把人家的`README.md`汉化整理了，结果发现它的[wiki页面](https://github.com/hexojs/hexo)下就有中文说明，心累啊

**Comment by hongri1995930** [comment]
@HuQinyang 蛤蛤，我去转载一下叫跟着清扬大神学前端（xue fan yi）

**Comment by ypgldhqz** [comment]
@hongri1995930 有趣

**Comment by hongri1995930** [comment]
@ypgldhqz Run dog ,what are you doing?

**Comment by ypgldhqz** [comment]
@hongri1995930 just see see sun dog
